title: Daniel Scott
description: Essays, Reviews, and Explorations
google_analytics: 
show_downloads: false
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions

gem "github-pages", group: :jekyll_plugins
